DROP TABLE IF EXISTS TRADE_STORE;
 
CREATE TABLE TRADE_STORE (
  	TRADE_ID VARCHAR(20),
	VERSION INT NOT NULL,
	COUNTER_PARTY_ID VARCHAR(20),
	BOOK_ID VARCHAR(20),
	BOOK_ID_MATURITY_DATE DATE,
	CREATED_DATE	DATE,
	EXPIRED VARCHAR(5) NOT NULL
);


	